import { jsPDF } from 'jspdf';

export const generatePDF = (content, title, type = 'document') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  
  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 30);
  
  // Subtitle/Type
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(type.replace('_', ' ').toUpperCase(), margin, 40);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, 48);
  
  // Reset text color
  doc.setTextColor(0);
  
  // Content
  doc.setFontSize(11);
  let y = 65;
  
  // Split content by lines and process markdown-like formatting
  const lines = content.split('\n');
  
  lines.forEach((line) => {
    // Check for page overflow
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    
    if (line.startsWith('# ')) {
      // H1
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      y += 10;
      doc.text(line.slice(2), margin, y);
      y += 8;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
    } else if (line.startsWith('## ')) {
      // H2
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      y += 8;
      doc.text(line.slice(3), margin, y);
      y += 6;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
    } else if (line.startsWith('### ')) {
      // H3
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      y += 6;
      doc.text(line.slice(4), margin, y);
      y += 5;
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      // Bullet point
      const bulletText = `• ${line.slice(2)}`;
      const splitText = doc.splitTextToSize(bulletText, maxWidth - 10);
      splitText.forEach((textLine) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(textLine, margin + 5, y);
        y += 6;
      });
    } else if (line.match(/^\d+\./)) {
      // Numbered list
      const splitText = doc.splitTextToSize(line, maxWidth - 10);
      splitText.forEach((textLine) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(textLine, margin + 5, y);
        y += 6;
      });
    } else if (line.trim() === '') {
      // Empty line
      y += 4;
    } else {
      // Regular paragraph
      const splitText = doc.splitTextToSize(line, maxWidth);
      splitText.forEach((textLine) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(textLine, margin, y);
        y += 6;
      });
    }
  });
  
  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: 'center' });
    doc.text('Generated by IdeaForge', margin, 290);
  }
  
  return doc;
};

export const downloadPDF = (content, title, type = 'document') => {
  const doc = generatePDF(content, title, type);
  const filename = `${title.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
};

export const generateAnalysisPDF = (project, analysis, scenario) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  
  // Title Page
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('Business Analysis Report', margin, 40);
  
  doc.setFontSize(18);
  doc.setFont('helvetica', 'normal');
  doc.text(project.name, margin, 55);
  
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, 70);
  doc.text(`Scenario: ${scenario}`, margin, 78);
  
  // Executive Summary
  doc.addPage();
  doc.setTextColor(0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', margin, 30);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  let y = 45;
  
  // Project Info
  doc.setFont('helvetica', 'bold');
  doc.text('Project Overview', margin, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  
  const projectInfo = [
    `Description: ${project.description}`,
    `Vision: ${project.vision}`,
    `Target Market: ${project.target_market}`,
    `Industry: ${project.industry}`,
  ];
  
  projectInfo.forEach((info) => {
    const splitText = doc.splitTextToSize(info, pageWidth - 2 * margin);
    splitText.forEach((line) => {
      doc.text(line, margin, y);
      y += 6;
    });
    y += 2;
  });
  
  // Comparative Analysis
  if (analysis?.comparative_analysis) {
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Comparative Analysis', margin, y);
    y += 10;
    doc.setFont('helvetica', 'normal');
    
    // Without solution
    doc.setFont('helvetica', 'bold');
    doc.text('Without Your Solution:', margin, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    
    const without = analysis.comparative_analysis.world_without_solution;
    if (without?.current_state) {
      const text = doc.splitTextToSize(without.current_state, pageWidth - 2 * margin);
      text.forEach((line) => {
        doc.text(line, margin, y);
        y += 6;
      });
    }
    
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.text('With Your Solution:', margin, y);
    y += 7;
    doc.setFont('helvetica', 'normal');
    
    const withSol = analysis.comparative_analysis.world_with_solution;
    if (withSol?.improved_state) {
      const text = doc.splitTextToSize(withSol.improved_state, pageWidth - 2 * margin);
      text.forEach((line) => {
        doc.text(line, margin, y);
        y += 6;
      });
    }
  }
  
  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, 290, { align: 'center' });
    doc.text('Generated by IdeaForge', margin, 290);
  }
  
  return doc;
};
